### ISSUE TITLE
AddChannelVersion failed with apostrophe in YAML

### ISSUE THREAD

**Issue by weimel** [IBM/satcon-client-go#35]
**Describe the bug**
Tried to upload large yaml (1737 lines, multiple resource definitions) using AddChannelVersion method. Received `encoding/json.SyntaxError: unexpected end of json input` Other file uploads have succeeded (~50 lines)

**Expected behavior**
Expected version to be successfully created like the other files.

**Actual behavior**
Could not upload version: `encoding/json.SyntaxError: unexpected end of json input`

**Steps To Reproduce**
How method was used:
````
fileBytes, err := ioutil.ReadFile(versionFile)
if err != nil {
return err
}
versionResp, err := satCon.Versions.AddChannelVersion(s.AccountID, s.ConfigID, versionName, fileBytes, versionDesc)
````
Result after `err := c.DoQuery(AddChannelVersionVarTemplate, vars, nil, &response` in AddChannelVersion
`encoding/json.SyntaxError: unexpected end of json input`

**Screenshots**

**Additional context**

**Comment by steven-collins-omega** [comment]
Our team has an internal corresponding issue to fix this, current ETA is by 16 July 2021 (subject to change)

**Comment by steven-collins-omega** [comment]
Turned out the problem wasn't the length of the YAML; we were incorrectly escaping characters when serializing to JSON.
